# Generated by Django 4.2.24 on 2025-09-28 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weeklybalances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('earnings', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('totalExpenses', models.IntegerField()),
                ('netProfit', models.IntegerField()),
                ('weeklyBalance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='weeklybalances.weeklybalance')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-date'],
            },
        ),
    ]
