# Generated by Django 4.2.24 on 2025-09-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expenses_weeklybalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
