# Generated by Django 4.2.24 on 2025-09-28 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxes', '0001_initial'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesBoxes',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.box')),
                ('boxControl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.boxcontrols')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expenses')),
            ],
            options={
                'verbose_name': 'Gasto de Caja',
                'verbose_name_plural': 'Gastos de Caja',
            },
        ),
    ]
