# Generated by Django 4.2.24 on 2025-09-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBalance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Balance Semanal',
                'verbose_name_plural': 'Balances Semanales',
                'ordering': ['-createdAt'],
            },
        ),
    ]
