# Generated by Django 4.2.24 on 2025-09-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('earnings', models.DecimalField(decimal_places=2, max_digits=15)),
                ('createdAt', models.DateTimeField()),
                ('generalExpenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('operatingExpenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('workerExpenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rentExpenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('motorcycleExpenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cornBags', models.IntegerField()),
                ('cornPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('charcoalBags', models.IntegerField()),
                ('charcoalPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('totalExpenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('netProfit', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
                'ordering': ['-date'],
            },
        ),
    ]
